# Generated by Django 4.0.3 on 2022-04-01 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0005_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 1, 16, 6, 9, 476621)),
        ),
    ]
