# Generated by Django 4.0.3 on 2022-04-01 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0006_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 1, 20, 27, 10, 167329)),
        ),
    ]
