# Generated by Django 4.0.3 on 2022-06-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0007_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 12, 29, 59, 419708)),
        ),
    ]
